import { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserMultiFormatReader } from '@zxing/browser';
import { api } from './api';
import './styles.css';

const nav = [['Dashboard','▦'],['Inventory','□'],['Expiry alerts','◷'],['CSV import','⇧'],['Scanner','⌁']];
const blank = {name:'', category:'Cooked Meals', quantity:'', unit:'kg', expiry_date:'', donor:'', barcode:'', notes:'', status:'available'};
const colors = ['#1769e0','#3093eb','#5aa8f5','#0e57bf','#7bbdff','#3f7fe8'];
function Badge({state, children}) { return <span className={`badge ${state}`}>{children}</span> }
function App() {
 const [page,setPage]=useState('Dashboard'), [dashboard,setDashboard]=useState(null), [items,setItems]=useState([]), [expiry,setExpiry]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState(''), [modal,setModal]=useState(null), [toast,setToast]=useState(''), [theme,setTheme]=useState(()=>localStorage.getItem('foodbridge-theme')||'light');
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('foodbridge-theme',theme)},[theme]);
 const notify=(text)=>{setToast(text); setTimeout(()=>setToast(''),3500)};
 const refresh=async()=>{setLoading(true); try {const [d,i,e]=await Promise.all([api.dashboard(),api.inventory(),api.expiry()]); setDashboard(d);setItems(i);setExpiry(e);setError('')}catch(err){setError(`Cannot reach FoodBridge API: ${err.message}`)}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]);
 const content=useMemo(()=> page==='Dashboard'? <Dashboard data={dashboard} items={items} openModal={setModal} /> : page==='Inventory'? <Inventory items={items} openModal={setModal} remove={async id=>{if(confirm('Remove this inventory item?')){await api.remove(id);notify('Item removed');refresh()}}} /> : page==='Expiry alerts'? <Expiry items={expiry} openModal={setModal}/> : page==='CSV import'? <CsvImport done={()=>{notify('CSV imported');refresh()}}/> : <Scanner found={(item)=>{setPage('Inventory');setModal(item)}}/>, [page,dashboard,items,expiry]);
 return <div className="app"><header><div className="brand"><span className="logo">▯</span><div><b>FoodBridge</b><small>AI Food Waste Reduction Platform</small></div></div><nav>{['Dashboard','Inventory','Expiry'].map(x=><button className={page===x?'active':''} onClick={()=>setPage(x)} key={x}>{x}</button>)}</nav><button className="theme-toggle" type="button" onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label={`Switch to ${theme==='light'?'dark':'light'} theme`} title={`Switch to ${theme==='light'?'dark':'light'} theme`}>{theme==='light'?'◐ Dark':'◑ Light'}</button><div className="avatar">AP<br/><small>Admin</small></div></header><aside>{nav.map(([label,icon])=><button className={page===label?'selected':''} key={label} onClick={()=>setPage(label)}><i>{icon}</i>{label}</button>)}</aside><main>{error?<div className="error"><b>FoodBridge could not load.</b><span>{error}</span><button className="primary" onClick={refresh}>Retry connection</button></div>:loading?<div className="loading">Loading FoodBridge…</div>:content}</main>{modal&&<ItemModal item={modal==='new'?null:modal} close={()=>setModal(null)} done={()=>{setModal(null);notify('Inventory saved');refresh()}}/>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}
function Dashboard({data,items,openModal}) { if(!data)return null; const max=Math.max(...data.by_category.map(x=>x.quantity),1); return <><section className="title"><div><h1>Food Rescue Dashboard</h1><p>Manage surplus food inventory before it goes to waste.</p></div><button className="primary" onClick={()=>openModal('new')}>+ New listing</button></section><section className="metrics"><Metric label="Listings active" value={data.metrics.active_listings} hint="ready for distribution" tone="green"/><Metric label="Food available" value={`${data.metrics.available_kg} kg`} hint="in current inventory" tone="orange"/><Metric label="Expiry alerts" value={data.metrics.expiring_soon} hint="within 24 hours" tone="blue"/><Metric label="Donors active" value={data.metrics.donors} hint="contributing partners" tone="purple"/></section><section className="dashboard-grid"><div className="panel chart"><h3>Inventory by category <span>(kg)</span></h3><div className="bars">{data.by_category.map((x,i)=><div className="bar-wrap" key={x.category}><b>{x.quantity}</b><div className="bar" style={{height:`${Math.max(16,x.quantity/max*155)}px`,background:colors[i%colors.length]}}/><small>{x.category}</small></div>)}</div></div><div className="panel donors"><h3>Top donor partners <em>live</em></h3>{data.top_donors.map((x,i)=><div className="donor" key={x.donor}><span style={{background:colors[i]}}></span>{x.donor}<b>{x.quantity} kg</b></div>)}</div></section><section className="panel table-panel"><h3>Current inventory</h3><InventoryTable items={items.slice(0,6)}/></section></> }
function Metric({label,value,hint,tone}) {return <div className={`metric ${tone}`}><span>{label}</span><b>{value}</b><small>{hint}</small></div>}
function Inventory({items,openModal,remove}) {const [query,setQuery]=useState(''); const shown=items.filter(i=>`${i.name} ${i.donor} ${i.category}`.toLowerCase().includes(query.toLowerCase()));return <><section className="title"><div><h1>Inventory management</h1><p>Add, update and prioritize donated food items.</p></div><button className="primary" onClick={()=>openModal('new')}>+ Add item</button></section><div className="toolbar"><input placeholder="Search food, donor or category…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{shown.length} items</span></div><section className="panel table-panel"><InventoryTable items={shown} actions={(item)=><><button onClick={()=>openModal(item)}>Edit</button><button className="danger" onClick={()=>remove(item.id)}>Remove</button></>}/></section></>}
function InventoryTable({items,actions}) {return <table><thead><tr><th>Item</th><th>Donor</th><th>Category</th><th>Quantity</th><th>Expires</th><th>Status</th>{actions&&<th/>}</tr></thead><tbody>{items.map(i=><tr key={i.id}><td><b>{i.name}</b><small>{i.barcode||'No barcode'}</small></td><td>{i.donor}</td><td>{i.category}</td><td>{i.quantity} {i.unit}</td><td><Badge state={i.expiry_state}>{i.expiry_state==='expired'?'Expired':i.days_to_expiry===0?'Today':`${i.days_to_expiry} days`}</Badge></td><td><Badge state={i.status}>{i.status}</Badge></td>{actions&&<td className="actions">{actions(i)}</td>}</tr>)}</tbody></table>}
function Expiry({items,openModal}) {return <><section className="title"><div><h1>Expiry tracking</h1><p>Prioritize pickup and distribution for perishable food.</p></div></section><div className="alert-card"><b>{items.filter(i=>i.expiry_state==='expired').length} expired</b><span>Remove or review expired stock promptly.</span></div><section className="panel table-panel"><InventoryTable items={items} actions={i=><button onClick={()=>openModal(i)}>Review</button>}/></section></>}
function CsvImport({done}) {const [file,setFile]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const upload=async()=>{if(!file)return;setBusy(true);try{const r=await api.importCsv(file);setMessage(`${r.added} items imported${r.errors.length?`; ${r.errors.length} rows need attention`:''}`);if(r.added)done()}catch(e){setMessage(e.message)}finally{setBusy(false)}};return <><section className="title"><div><h1>Import inventory</h1><p>Bulk-add food donations from a CSV file.</p></div></section><section className="panel import"><div className="upload-icon">⇧</div><h2>Upload a CSV file</h2><p>Required columns: name, category, quantity, unit, expiry_date, donor.<br/>Optional: barcode, notes.</p><input type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files[0])}/>{file&&<b>{file.name}</b>}<button className="primary" disabled={!file||busy} onClick={upload}>{busy?'Importing…':'Import inventory'}</button>{message&&<div className="import-result">{message}</div>}</section></>}
function Scanner({found}) {const [code,setCode]=useState(''),[status,setStatus]=useState('Use a USB scanner, enter a code, or start camera scanning.'); const video=useRef(null), reader=useRef(null);const lookup=async value=>{const scannedCode=value.trim();if(!scannedCode){setStatus('Enter or scan a barcode or QR value first.');return}try{const item=await api.scan(scannedCode);setStatus('Item found. Opening its details…');found(item)}catch(e){setStatus(e.message)}};const camera=async()=>{try{reader.current=new BrowserMultiFormatReader();await reader.current.decodeFromVideoDevice(undefined,video.current,(result)=>{if(result){reader.current.reset();lookup(result.getText())}});setStatus('Point the camera at a barcode or QR code.')}catch(e){setStatus(`Camera unavailable: ${e.message}`)}};useEffect(()=>()=>reader.current?.reset(),[]);return <><section className="title"><div><h1>Barcode & QR scanner</h1><p>Find an item instantly by its FoodBridge code.</p></div></section><section className="panel scanner"><video ref={video} muted/><div><h2>Scan inventory</h2><p aria-live="polite">{status}</p><div className="scan-row"><input value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&lookup(code)} placeholder="e.g. FB-1001"/><button className="primary" onClick={()=>lookup(code)}>Lookup</button></div><button onClick={camera}>Start camera scanner</button><small>Camera scanning uses ZXing and is ready for supported desktop/mobile cameras.</small></div></section></>}
function ItemModal({item,close,done}) {const [form,setForm]=useState(item?{...item,expiry_date:item.expiry_date}:blank),[error,setError]=useState(''),[busy,setBusy]=useState(false); const set=(k,v)=>setForm({...form,[k]:v});const submit=async e=>{e.preventDefault();setBusy(true);try{const body={...form,quantity:Number(form.quantity)};item?await api.update(item.id,body):await api.create(body);done()}catch(err){setError(err.message)}finally{setBusy(false)}};return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><h2>{item?'Update inventory':'Add inventory item'}</h2><button type="button" onClick={close}>×</button></div><div className="form-grid">{[['name','Food item'],['donor','Donor'],['category','Category'],['quantity','Quantity'],['unit','Unit'],['expiry_date','Expiry date'],['barcode','Barcode / QR value'],['notes','Notes']].map(([key,label])=><label key={key}>{label}{key==='category'?<select value={form[key]} onChange={e=>set(key,e.target.value)}>{['Cooked Meals','Bakery','Fruits & Veg','Dairy','Grains','Packaged'].map(x=><option key={x}>{x}</option>)}</select>:<input required={['name','donor','quantity','expiry_date'].includes(key)} type={key==='expiry_date'?'date':key==='quantity'?'number':'text'} step="0.1" value={form[key]??''} onChange={e=>set(key,e.target.value)}/>}</label>)}{item&&<label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}>{['available','reserved','distributed'].map(x=><option key={x}>{x}</option>)}</select></label>}</div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save item'}</button></div></form></div>}
createRoot(document.getElementById('root')).render(<App/>);
